[package]
name = "vernum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8", features = ["std_rng"] }
num-bigint = { version = "0.4", features = ["rand"] }
